/** Translate system labels only; custom names and stored identifiers stay intact. */
const labels: Record<string, string> = {
  DayOff: "Dam olish kuni",
  DAY_OFF_CREATE: "Dam olish kuni belgilandi",
  DAY_OFF_CANCEL: "Dam olish kuni bekor qilindi",
  SUPER_ADMIN: "Bosh administrator",
  ADMIN: "Administrator",
  EMPLOYEE: "Xodim",
  "Engine Oil Change": "Dvigatel moyini almashtirish",
  "Oil Filter": "Moy filtri",
  "Air Filter": "Havo filtri",
  "Brake Pads": "Tormoz kolodkalari",
  "Tire Change": "Shina almashtirish",
  "Battery Change": "Akkumulyator almashtirish",
  "Car Wash": "Avtomobil yuvish",
  Detailing: "Avtomobilni chuqur tozalash",
  Repair: "Ta’mirlash",
  Diagnostics: "Tashxislash",
  Other: "Boshqa",
  "Rental Agreement": "Ijara shartnomasi",
  Insurance: "Sug‘urta",
  "Tint Permit": "Oynani qoraytirish ruxsatnomasi",
  AVAILABLE: "Bo‘sh",
  RENTED: "Band",
  SERVICE: "Servisda",
  RESERVED: "Oldindan band qilingan",
  UNAVAILABLE: "Mavjud emas",
  WITH_OWNER: "Egasida",
  CAR_WASH: "Avtomobil yuvish joyida",
  CREATE: "Yaratildi",
  UPDATE: "Yangilandi",
  DELETE: "O‘chirildi",
  ARCHIVE: "Arxivlandi",
  LOGIN: "Tizimga kirildi",
  LOGOUT: "Tizimdan chiqildi",
  LOGOUT_ALL: "Barcha qurilmalardan chiqildi",
  CHECK_IN: "Ishga kelish qayd etildi",
  CHECK_OUT: "Ishdan ketish qayd etildi",
  ADMIN_EDIT: "Administrator tahrirladi",
  ADMIN_DELETE: "Administrator o‘chirdi",
  STATUS_CHANGE: "Holat o‘zgartirildi",
  AUTO_RELEASE: "Avtomatik bo‘shatildi",
  TELEGRAM_VERIFIED: "Telegram tasdiqlandi",
  TELEGRAM_LOGIN: "Telegram orqali kirildi",
  RESET_NOTIFICATIONS: "Bildirishnomalar tozalandi",
  User: "Foydalanuvchi",
  Car: "Avtomobil",
  CarService: "Servis yozuvi",
  CarDocument: "Avtomobil hujjati",
  Attendance: "Davomat",
  DailyTask: "Kunlik ish",
  Notification: "Bildirishnoma",
  AuditLog: "Amallar tarixi",
  Office: "Ofis",
  ServiceType: "Servis turi",
  DocumentType: "Hujjat turi",
  RentalRecord: "Ijara yozuvi",
  GoogleSheetsConfig: "Google jadvali sozlamalari",
  SystemSetting: "Tizim sozlamasi",
};
export function uzLabel(value: string) {
  return labels[value] || value;
}
